// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNixhmJ4McdMhNuAIk6vwSFDuksV9enCI',
    appId: '1:889122319745:android:c278633f202a64cc928c80',
    messagingSenderId: '889122319745',
    projectId: 'store-retrive-data-project',
    databaseURL: 'https://store-retrive-data-project.firebaseio.com',
    storageBucket: 'store-retrive-data-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-B5y0262ffrzyKpyORkhzf3tcmXkD9Uo',
    appId: '1:889122319745:ios:a6562354dd12f5aa928c80',
    messagingSenderId: '889122319745',
    projectId: 'store-retrive-data-project',
    databaseURL: 'https://store-retrive-data-project.firebaseio.com',
    storageBucket: 'store-retrive-data-project.appspot.com',
    androidClientId: '889122319745-3irufiotf5slj0ugmm8bvl8idfpbjv1t.apps.googleusercontent.com',
    iosClientId: '889122319745-hf7kqn33dinmnaa6j3kbfmohtkd6o5io.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
